name: foundation_flutter
description:
version: 0.0.3
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git
    
  intl: any