name: foundation_flutter
description:
version: 0.0.3
homepage:
publish_to: none

environment:
  sdk: '>=3.3.1 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  pshondation:
    git:
      url: https://github.com/pshonkaaa/package.pshondation.dart.git
  
  web: any
    
  intl: any